### ISSUE TITLE
dulwich: properly patch credentials

### ISSUE THREAD

**Issue by efiop** [iterative/scmrepo#147]
From @dtrifiro 

> I've had a quick look. Need to fix the clone method in scmrepo.git.backends.dulwich, it doesn't use the GitCredentials client. This needs to also be done in other methods which use get_transport_and_path

https://github.com/iterative/dvc/issues/7670

Looks like we need to copypaste clone(and other) implementations from dulwich and use our client instead of relying on `get_transport_and_path`.

**Comment by sisp** [comment]
See https://github.com/iterative/dvc/issues/7670#issuecomment-1319767594. This is really a blocker for macOS users. :slightly_frowning_face:

**Comment by dtrifiro** [comment]
My initial observations were not correct, the client is patched correctly and the following code works for private repos which require credential helpers on MacOS:

```python
from scmrepo.git import Git

git = Git(".")
git.clone("https://github.com/dtrifiro/a-private-repo", "a-private-repo")
# or, explicitly using the dulwich backend:
git.dulwich.clone("https://github.com/dtrifiro/a-private-repo", "a-private-repo")
```
