### ISSUE TITLE
dulwich: use subprocess ssh vendor if GIT_SSH or GIT_SSH_COMMAND env vars are set

### ISSUE THREAD

**Issue by pmrowla** [iterative/scmrepo#160]
We default to using asyncssh since we cannot rely on CLI `ssh` always being available. But if the user is setting `GIT_SSH_COMMAND` themselves we can assume the provided command is valid and we should prefer that over asyncssh (since it may have settings that are not in their `~/.ssh/config`)

**Comment by pmrowla** [comment]
Semi-related to https://github.com/iterative/dvc/issues/8681

After this is fixed using `GIT_SSH_COMMAND=ssh dvc ...` will force DVC to use CLI ssh instead of asyncssh for git operations which will workaround issues where asyncssh does not support certain OpenSSH configurations

**Comment by dberenbaum** [comment]
@pmrowla So the idea is to use the existing [Git env var](https://git-scm.com/docs/git#Documentation/git.txt-codeGITSSHcode)? Would a typical value for `GIT_SSH` be `ssh` for this purpose? Could you provide an example of how to use it? Do you want to document it in troubleshooting or somewhere?

**Comment by dberenbaum** [comment]
> Semi-related to [iterative/dvc#8681](https://github.com/iterative/dvc/issues/8681)

In this case (or others where asyncssh does not match cli ssh), would a workaround would be to explicitly set `GIT_SSH[_COMMAND]=ssh` to force dvc to use cli ssh? Is that something we should document in troubleshooting?

**Comment by pmrowla** [comment]
We could consider documenting it in troubleshooting, but IMO it would probably be better to prefer fixing things in scmrepo/asyncssh whenever there is an actual incompatibility w/OpenSSH configs (like #8681), and just suggest this as a temporary workaround when necessary

**Comment by pmrowla** [comment]
Also, just note that when suggesting this as a workaround, users probably want `GIT_SSH_COMMAND` and not `GIT_SSH` (they behave similarly but are not actually the same).

`GIT_SSH_COMMAND` executes the command through the user's shell, so things like `$PATH` and shell aliases are respected (so you can use `GIT_SSH_COMMAND=ssh`, which will search `$PATH` for the location of `ssh`).

`GIT_SSH` executes the raw command and does not use the shell (so you have to use explicit paths to the `ssh` command like `GIT_SSH=/usr/bin/ssh`)
