### ISSUE TITLE
exp run: can't stash changes (nothing to stash) on Win

### ISSUE THREAD

**Issue by shcheklein** [iterative/scmrepo#211]
# Bug Report

## Description

`dvc exp run` fails on Windows (conda) with an error from `pygit2`: `unexpected error - 'cannot stash changes - there is nothing to stash.'`

### Reproduce

I was using: Win 11, VS Code or miniconda terminal, https://github.com/shcheklein/hackathon repo w/o any substantial changes.

`dvc exp run` fails with this error from the very start.

**Output of `dvc doctor`:**

```console
DVC version: 2.41.1 (pip)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.22621-SP0
Subprojects:
        dvc_data = 0.29.0
        dvc_objects = 0.14.1
        dvc_render = 0.0.17
        dvc_task = 0.1.9
        dvclive = 1.3.2
        scmrepo = 0.1.5
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by pmrowla** [comment]
discord user reports possible merge conflict error (instead of the nothing to stash error) in some cases after #214 https://discord.com/channels/485586884165107732/1085840450218377216/1090263098994204753

**Comment by pmrowla** [comment]
Issue was that the repo contained `.gitattributes` EOL settings with files that had not been normalized to match the gitattributes settings

The workaround here is to do
```
git add . --renormalize
git commit
```
to make sure the files in the repo match the gitattributes settings before using `dvc exp run` (this should only need to be done once)
