### ISSUE TITLE
pygit: use anonymous remotes

### ISSUE THREAD

**Issue by pmrowla** [iterative/scmrepo#258]
This is probably another indicator that we should really be using `git_remote_add_anonymous` (since we technically are breaking the config until we actually hit our `finally:` cleanup block)

_Originally posted by @pmrowla in https://github.com/iterative/scmrepo/issues/177#issuecomment-1418775068_
            
User reports there are still cases where our temp remotes are getting written to git config, we need to just use explicitly anonymous remotes instead.

requires https://github.com/libgit2/pygit2/pull/1229

**Comment by shcheklein** [comment]
@pmrowla it seems it's breaking the Studio update (gto depends on the latest scmrepo). The symptom I see, is that we are getting: exp refs like:

```
2023-10-27 23:08:29,525 DEBUG scmrepo.git.backend.pygit2 fetch_refspecs: ['+refs/exps/72/31aed430fff6728c2057c6a5985a138725c70b/itchy-cham:refs/remotes/None/exps/72/31aed430fff6728c2057c6a5985a138725c70b/itchy-cham']
```

Mind the `None` part in the ref name.

It might be breaking some merge logic (when exp already exists locally). I can confirm that.
