### ISSUE TITLE
Version restriction on asyncssh

### ISSUE THREAD

**Issue by ghisvail** [iterative/scmrepo#43]
What are the rationales for the version restrictions for `asyncssh`:

`asyncssh>=2.7.1,<2.9`

It currently makes `dvc` uninstallable on Nix due to `asyncssh` being newer.

I was wondering whether the upper bound could be dropped?

**Comment by pmrowla** [comment]
It's to match https://github.com/fsspec/sshfs but in both cases the restrictions just weren't tested/updated when asyncssh released 2.9.

We should probably just change the upper restriction to the next major version instead of minor (so < 3 instead of <2.x)

**Comment by ghisvail** [comment]
> It's to match https://github.com/fsspec/sshfs but in both cases the restrictions just weren't tested/updated when asyncssh released 2.9.

I am not quite sure I follow. You are not depending on `sshfs` directly, are you?

**Comment by pmrowla** [comment]
> I am not quite sure I follow. You are not depending on `sshfs` directly, are you?

This package does not depend on `sshfs`, but DVC does, so supporting `asyncssh` 2.9 in `scmrepo` but not `sshfs` would not work as a solution to your issue
